version: "3.4"
services:

  nginx:
    container_name: "loadBalancer"
    build:
      context: "./services/nginx"
      dockerfile: dockerfile
    ports:
      - "80:80"
    networks:
      - "netengine"

  api:
    container_name: "app_ousf"
    build:
      context: "./"
      dockerfile: dockerfile
    
    ports:
      - "${PORT}:${PORT}"

    networks:
      - "netengine"

  mongo:
    container_name: mongodb_ousf
    image: mongo:4.2

    volumes:
      - ./data/dataMongo:/data/db:rw

    ports:
      - ${MONGO_DB_PORT}:27017
    
    networks:
      - "netengine"
      



networks:
  netengine: 
    name: netengine
    driver: bridge

